<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-01T22:46:55 IST" name="testsuite" finished-at="2023-12-01T22:47:09 IST" duration-ms="13501">
    <groups>
    </groups>
    <test started-at="2023-12-01T22:46:55 IST" name="MyFramework" finished-at="2023-12-01T22:47:09 IST" duration-ms="13501">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="InitalizeExtentReport()[pri:0, instance:tests.LoginTest@609e8838]" started-at="2023-12-01T22:46:55 IST" name="InitalizeExtentReport" finished-at="2023-12-01T22:46:55 IST" duration-ms="191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitalizeExtentReport -->
        <test-method is-config="true" signature="getnameMethod(org.testng.ITestContext)[pri:0, instance:tests.LoginTest@609e8838]" started-at="2023-12-01T22:46:55 IST" name="getnameMethod" finished-at="2023-12-01T22:46:55 IST" duration-ms="10" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5167268]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getnameMethod -->
        <test-method is-config="true" signature="start_browser()[pri:0, instance:tests.LoginTest@609e8838]" started-at="2023-12-01T22:46:55 IST" name="start_browser" finished-at="2023-12-01T22:47:02 IST" depends-on-methods="pages.TestBase.getnameMethod" duration-ms="6339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start_browser -->
        <test-method signature="test_login(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@609e8838]" started-at="2023-12-01T22:47:03 IST" name="test_login" data-provider="LoginDetails" finished-at="2023-12-01T22:47:03 IST" duration-ms="776" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[no logout]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: no logout
at org.testng.Assert.fail(Assert.java:110)
at tests.LoginTest.test_login(LoginTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_login -->
        <test-method is-config="true" signature="generateTestStatus(java.lang.reflect.Method,org.testng.ITestResult)[pri:0, instance:tests.LoginTest@609e8838]" started-at="2023-12-01T22:47:03 IST" name="generateTestStatus" finished-at="2023-12-01T22:47:04 IST" duration-ms="267" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTest.test_login(java.lang.String,java.lang.String) throws java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=test_login status=FAILURE method=LoginTest.test_login(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@609e8838] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateTestStatus -->
        <test-method signature="test_login(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@609e8838]" started-at="2023-12-01T22:47:04 IST" name="test_login" data-provider="LoginDetails" finished-at="2023-12-01T22:47:08 IST" duration-ms="3923" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[seleniumjava@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sel123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_login -->
        <test-method is-config="true" signature="generateTestStatus(java.lang.reflect.Method,org.testng.ITestResult)[pri:0, instance:tests.LoginTest@609e8838]" started-at="2023-12-01T22:47:08 IST" name="generateTestStatus" finished-at="2023-12-01T22:47:08 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTest.test_login(java.lang.String,java.lang.String) throws java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=test_login status=SUCCESS method=LoginTest.test_login(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@609e8838] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateTestStatus -->
        <test-method signature="test_login(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@609e8838]" started-at="2023-12-01T22:47:08 IST" name="test_login" data-provider="LoginDetails" finished-at="2023-12-01T22:47:08 IST" duration-ms="769" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mercury]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mercury123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[no logout]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: no logout
at org.testng.Assert.fail(Assert.java:110)
at tests.LoginTest.test_login(LoginTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_login -->
        <test-method is-config="true" signature="generateTestStatus(java.lang.reflect.Method,org.testng.ITestResult)[pri:0, instance:tests.LoginTest@609e8838]" started-at="2023-12-01T22:47:08 IST" name="generateTestStatus" finished-at="2023-12-01T22:47:08 IST" duration-ms="194" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTest.test_login(java.lang.String,java.lang.String) throws java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=test_login status=FAILURE method=LoginTest.test_login(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@609e8838] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateTestStatus -->
        <test-method is-config="true" signature="close_browser()[pri:0, instance:tests.LoginTest@609e8838]" started-at="2023-12-01T22:47:09 IST" name="close_browser" finished-at="2023-12-01T22:47:09 IST" duration-ms="166" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_browser -->
        <test-method is-config="true" signature="generateReports()[pri:0, instance:tests.LoginTest@609e8838]" started-at="2023-12-01T22:47:09 IST" name="generateReports" finished-at="2023-12-01T22:47:09 IST" duration-ms="783" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReports -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- MyFramework -->
  </suite> <!-- testsuite -->
</testng-results>
