<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LenovoIdeaPad" failures="2" tests="3" name="MyFramework" time="13.501" errors="0" timestamp="2023-12-01T22:47:09 IST">
  <testcase classname="tests.LoginTest" name="test_login" time="0.776">
    <failure type="java.lang.AssertionError" message="no logout">
      <![CDATA[java.lang.AssertionError: no logout
at tests.LoginTest.test_login(LoginTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- test_login -->
  <testcase classname="tests.LoginTest" name="test_login" time="3.923"/>
  <testcase classname="tests.LoginTest" name="test_login" time="0.769">
    <failure type="java.lang.AssertionError" message="no logout">
      <![CDATA[java.lang.AssertionError: no logout
at tests.LoginTest.test_login(LoginTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- test_login -->
</testsuite> <!-- MyFramework -->
